platform :ios, '9.3'
target 'bellarune' do
  use_frameworks!
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/RemoteConfig', '~> 5.3.0'
end
